-- AlterTable
ALTER TABLE `user` ADD COLUMN `isAccountVerified` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `resetOtp` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `resetOtpExpireAt` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `verifyOtp` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `verifyOtpExpireAt` INTEGER NOT NULL DEFAULT 0;
